[package]
name = "erlexec"
version = "0.1.0"
authors = ["Dmytro Lytovchenko <dmytro.lytovchenko@gmail.com>"]
edition = "2018"

[dependencies]
erlangrt = {path = "../lib-erlangrt"}
log = "0.4"
env_logger = "0.9"